print('Paciência Acordeão')
print('==================')
print('')
print('Seja bem-vindo(a) ao jogo de Paciência Acordeão! O objetico deste jogo é colocar todas as cartas em uma mesma pilha.')
print('')
print('{0}{1}{2}'.format('\033[1m', 'Regras do Jogo', '\033[0m'))
print('')
print('Existem apaenas dois movimentos possíveis:')
print('')
print('1. Empilhar uma carta sobre a carta imediatamente anterior;')
print('2. Empilhar uma carta sobre a terceira carta anterior.')
print('')
print('Para que um movimento possa ser realizado basta que uma das duas condições abaixo seja atendida:')
print('')
print("1. As duas cartas possuem o mesmo valor ou")
print("2. As duas cartas possuem o mesmo naipe.")
print('')
print("Desde que alguma das condições acima seja satisfeita, qualquer carta pode ser movimentada.")
print('')
print(input('Aperte [Enter] para continuar...'))
print('')
print('O estado atual do baralho é:')
print('')
print('1.  K♣ ')
print('2.  3♠ ')
print('')
numero_da_carta= int(input('Escolha uma carta (digite um número entre 1 e 52):'))

if numero_da_carta > 52 or numero_da_carta < 1:
    novo_numero = int(input('Posição inválida. Por favor, digite um número entre 1 e 52):'))
else:
    numero_da_carta 

